from collections.abc import Iterable

class DPMatrix:
    m: int
    n: int
    def __init__(self, reference: str, query: str): ...
    def set_entry(self, i: int, j: int, cost: int) -> None: ...

class Aligner:
    def __init__(
        self,
        reference: str,
        max_error_rate: float,
        flags: int = 15,
        wildcard_ref: bool = False,
        wildcard_query: bool = False,
        indel_cost: int = 1,
        min_overlap: int = 1,
        matching_policy: str = "default",
    ): ...
    def _set_reference(self, reference: str) -> None: ...
    @property
    def dpmatrix(self) -> DPMatrix: ...
    def scorematrix(self) -> DPMatrix: ...
    def enable_debug(self) -> None: ...
    def locate(self, query: str) -> tuple[int, int, int, int, int, int] | None: ...

class PrefixComparer:
    @property
    def effective_length(self) -> int: ...
    def __init__(
        self,
        reference: str,
        max_error_rate: float,
        wildcard_ref: bool = False,
        wildcard_query: bool = False,
        min_overlap: int = 1,
        matching_policy: str = "default",
    ): ...
    def locate(self, query: str) -> tuple[int, int, int, int, int, int] | None: ...

class SuffixComparer(PrefixComparer): ...

def hamming_sphere(s: str, k: int) -> Iterable[str]: ...
def edit_environment(t: str, k: int) -> Iterable[tuple[str, int, int]]: ...
