version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      # We need the most recent tag for setuptools_scm
      - git fetch --unshallow
python:
  install:
  - requirements: doc/requirements.txt
