#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2010 Marcel Martin <marcel.martin@tu-dortmund.de>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

"""%prog [options] <FASTA/FASTQ FILE> [<QUALITY FILE>]

Reads a FASTA or FASTQ file, finds and removes adapters,
and writes the changed sequence to standard output.
When finished, statistics are printed to standard error.

If two file names are given, they are assumed to be
.csfasta and .qual files as produced by the SOLiD sequencer.
(You still need to provide the -c option to correctly deal
with color space.)

If you want to search for the reverse complement of an adapter, you must
provide an additional adapter sequence.

If the input sequences are in color space, the adapter must
also be provided in color space (using a string of digits 0123).

Use --help to see all options.
"""

from __future__ import print_function, division

import sys, re
from string import maketrans
from optparse import OptionParser
from itertools import izip

from calign import semiglobalalign
import fasta


class FormatError(Exception):
	pass


class Error(Exception):
	pass


def print_statistics(adapters, stats, outfile=sys.stderr):
	print("# There are %7d sequences in this data set." % stats.n, file=outfile)
	print(file=outfile)
	#print("middle:", stats.middle, file=outfile)
	for adapter_index, adapter in enumerate(adapters):
		print("# Statistics for adapter %s (%s, length %d)" % (adapter_index+1, adapter, len(adapter)), file=outfile)
		#print "# The histograms follow: length of adapter vs. no. of sequences"
		print("#", file=outfile)
		print("# adapter found in the beginning of the sequence", file=outfile)
		print("# length\tnumber", file=outfile)
		total = 0
		for k, v in stats.lengths_front[adapter_index].items():
			print("%d\t%d" % (k, v), file=outfile)
			total += v
		print("total:", total, file=outfile)
		print(file=outfile)
		print(file=outfile)
		print("# adapter found at the end of the sequence", file=outfile)
		print("# length\tnumber", file=outfile)
		total = 0
		for k, v in stats.lengths_back[adapter_index].items():
			print("%d\t%d" % (k, v), file=outfile)
			total += v
		print("total:", total, file=outfile)
		print(file=outfile)
		print(file=outfile)


def quality_to_ascii(quality_line, base=33):
	"""
	Convert a string containing qualities given as integer to a string of ASCII-encoded qualities.

	base -- ASCII code of quality zero (sensible values are 33 and 64).

	>>> quality_to_ascii("17 4 29 18")
	'2%>3'
	"""
	fields = map(int, quality_line.split())
	qualities = ''.join(chr(q+base) for q in fields)
	return qualities


def find_best_alignment(adapters, seq):
	"""
	Find the best matching adapter.

	Return tuple (best_alignment, best_index).

	best_alignment is an alignment as returned by semiglobalalign.
	best_index is the index of the best adapter into the adapters list.
	"""
	assert adapters
	best_score = -1000000
	for index, adapter in enumerate(adapters):
		alignment = semiglobalalign(adapter, seq)
		(r1, r2, astart, astop, rstart, rstop, errors) = alignment
		# the length of the matching part of the adapter minus errors
		# determines which adapter fits best
		score = astop - astart - errors
		if score > best_score:
			best_alignment = alignment
			best_score = score
			best_index = index
	return (best_alignment, best_index)


def read_sequences(seqfilename, qualityfilename, colorspace):
	"""
	Read sequences and (if available) quality information from either:
	* seqfilename in FASTA format (qualityfilename must be None)
	* seqfilename in FASTQ format (qualityfilename must be None)
	* seqfilename in .csfasta format and qualityfilename in .qual format (SOLiD)

	Return a generator over tuples (description, sequence, qualities).
	qualities is None if no qualities are available.
	"""
	ftype = fasta.fastafiletype(seqfilename)

	if ftype == 'FASTQ' and qualityfilename is not None:
		raise Error, "If a FASTQ file is given, no quality file can be provided."

	if ftype == 'FASTQ':
		with open(seqfilename) as seqfile:
			for desc, seq, qualities in fasta.readfastq(seqfile, colorspace=colorspace):
				yield (desc, seq, qualities)
	elif ftype == 'FASTA' and qualityfilename is None:
		with open(seqfilename) as seqfile:
			for desc, seq in fasta.readfasta(seqfile):
				yield (desc, seq, None)
	else:
		assert ftype == 'FASTA' and qualityfilename is not None
		lengthdiff = 1 if colorspace else 0
		with open(seqfilename) as seqfile:
			with open(qualityfilename) as qualityfile:
				seq_iter = fasta.readfasta(seqfile)
				qual_iter = fasta.readfasta(qualityfile)
				for (qdesc, qseq), (rdesc, rseq) in izip(qual_iter, seq_iter):
					if qdesc != rdesc:
						raise FormatError, "Descriptions in FASTA and quality file don't match (%s and %s)." % (rdesc, qdesc)
					qualities = quality_to_ascii(qseq)
					assert len(qualities) == len(rseq) - lengthdiff, "%d != %d-x" % (len(qualities), len(rseq))
					yield rdesc, rseq, qualities


def main():
	parser = OptionParser(usage=__doc__)
	parser.add_option("-e", "--error-rate", type=float, default=0.1,
		help="Maximum allowed error rate (no. of errors divided by the length of the matching region) (default: %default)")
	parser.add_option("-o", "--output", default=None,
		help="The modified sequence gets written to this file (in FASTA format) (default: standard output)")
	parser.add_option("-a", "--adapters", action="append",
		help="Adapter sequences (use multiple -a options to search for more than one adapter)")
	parser.add_option("-n", "--times", type=int, metavar="count", default=1,
		help="Try to remove adapters at most COUNT times. Useful when an adapter gets appended multiple times.")
	#parser.add_option("--front", action='store_true', default=False,
		#help="Allow adapters to occur in the front of the read.") TODO adapter overlapping the front?
	parser.add_option("-r", "--rest-file", default=None,
		help="When the adapter matches in the middle of a read, write the rest (after the adapter) into a file. Use - for standard output.")
	parser.add_option("-x", "--prefix", default='',
		help="Add this prefix to read names")
	parser.add_option("-y", "--suffix", default='',
		help="Add this suffix to read names")
	parser.add_option("-c", "--colorspace", action='store_true', default=False,
		help="Colorspace mode: Trims adapter correctly (one more character than there are matches needs to be trimmed).")
	parser.add_option("-d", "--double-encode", action='store_true', default=False,
		help="When in color space, double-encode colors (mapping 0,1,2,3,4 to A,C,G,T,N).")
	parser.add_option("-t", "--trim-primer", action='store_true', default=False,
		help="When in color space, trim primer base and the transition to the first color")
	parser.add_option("--strip-f3", action='store_true', default=False,
		help="When in color space, strip the _F3 suffix of read names")
	parser.add_option("--maq", "--bwa", action='store_true', default=False,
		help="MAQ/BWA-compatible color space output. This enables -c, -d, -t, --strip-f3 and -y '/1'.")

	options, args = parser.parse_args()

	if len(args) == 0:
		parser.error("At least one parameter needed: name of the FASTA or FASTQ file.")
	elif len(args) > 2:
		parser.error("Too many parameters.")

	infilename = args[0]
	quality_filename = None
	if len(args) == 2:
		quality_filename = args[1]
		print("will use qualities from", quality_filename, file=sys.stderr)

	if options.output is None:
		outfile = sys.stdout
	else:
		outfile = open(options.output, 'w')

	if options.maq:
		options.colorspace = True
		options.double_encode = True
		options.trim_primer = True
		options.strip_f3 = True
		options.suffix = "/1"

	if options.trim_primer and not options.colorspace:
		parser.error("trimming the primer makes only sense in colorspace")
	if options.double_encode and not options.colorspace:
		parser.error("double-encoding makes only sense in colorspace")

	print("maximum error rate: %.2f%%" % (options.error_rate*100.), file=sys.stderr)
	times = options.times

	if options.rest_file:
		if options.rest_file == '-':
			rest_file = sys.stdout
		else:
			rest_file = open(options.rest_file, 'w')
	else:
		rest_file = None

	show_progress = False
	max_error_rate = options.error_rate

	if not options.adapters:
		print("You need to provide at least one adapter sequence.", file=sys.stderr)
		sys.exit(1)

	class Statistics(object):
		pass
	stats = Statistics()
	stats.middle = 0
	stats.adapter_matches = len(options.adapters)*[0]
	stats.sequence_matches = len(options.adapters)*[0]
	stats.lengths_front = []
	stats.lengths_back = []
	for x in xrange(len(options.adapters)):
		stats.lengths_front.append({})
	for x in xrange(len(options.adapters)):
		stats.lengths_back.append({})

	# for double-encoding colorspace sequences
	trans = maketrans('0123.', 'ACGTN')

	# length difference between sequence and qualities
	lengthdiff = 0 if options.trim_primer else 1

	n = 0
	qualities = None
	for (desc, seq, qualities) in read_sequences(infilename, quality_filename, colorspace=options.colorspace):
		n += 1
		if show_progress and n % 10000 == 0:
			print("Processing read no.", n, file=sys.stderr)

		# count number of adapters that match
		match = 0

		# In colorspace, the first character is the last nucleotide of the primer base
		# and the second character encodes the transition from the primer base to the
		# first real base of the read.
		if options.trim_primer:
			seq = seq[2:]
			if qualities is not None:
				qualities = qualities[1:]
			initial = ''
		elif options.colorspace:
			initial = seq[0]
			seq = seq[1:]
		else:
			initial = ''


		# try (possibly more than once) to remove an adapter
		for t in xrange(times):
			alignment, index = find_best_alignment(options.adapters, seq)
			(r1, r2, astart, astop, rstart, rstop, errors) = alignment
			length = astop - astart
			if length == 0 or errors/length > max_error_rate:
				break
			assert length-errors > 0

			adapter = options.adapters[index]
			# TODO temporary
			alen = len(adapter)
			rlen = len(seq)

			if rstart == 0 and rstop == len(seq):
				# The adapter or parts of it covers the entire read (case 1)
				assert r1[0] != '-' and r1[-1] != '-'
				assert rstart == 0 and rstop == len(seq)
				seq = ''
				if qualities is not None:
					qualities = ''
			elif rstart > 0:
				# The adapter is at the end of the read (case 2) or in the middle (case 3)
				assert r1[0] == '-'
				assert not (rstart == 0 and rstop == len(seq))
				assert astart == 0
				assert rstart > 0
				assert r2[0] != '-' # since that only happens when the adapter is in the front

				if rstop < rlen:
					# The adapter is in the middle of the read (case 3)
					assert r1[-1] == '-'
					stats.middle += 1
					if rest_file is not None:
						assert seq+length == rstop
						print(seq[rstop:], file=rest_file)
				# TODO defaultdict?
				stats.lengths_back[index][length] = stats.lengths_back[index].get(length, 0) + 1

				if options.colorspace:
					# trim one more color
					rstart -= 1
				seq = seq[:rstart]
				if qualities is not None:
					qualities = qualities[:rstart]
					assert len(qualities) == len(seq)
			else:
				# The adapter is in the beginning of the read (case 4)
				# TODO should this case be ignored in color space?
				assert r1[-1] == '-'
				assert not (rstart == 0 and rstop == len(seq))
				assert rstart == 0
				if True:
					stats.lengths_front[index][length] = stats.lengths_front[index].get(length, 0) + 1
					seq = seq[rstop:]
					if qualities is not None:
						qualities = qualities[rstop:]
			match += 1
			stats.adapter_matches[index] += 1
			stats.sequence_matches[index] += 1

		# other modifications to the sequence or its description
		# change any length=XX that may appear in the read description (for 454)
		desc = re.sub(r"\blength=[0-9]*\b", "length=%d" % len(seq), desc)

		if options.strip_f3 and desc.endswith('_F3'):
			desc = desc[:-3]
		desc = options.prefix + desc + options.suffix
		if options.double_encode:
			# convert color space sequence to double-encoded colorspace (using
			# characters ACGTN to represent colors)
			seq = seq.translate(trans)

		# write modified sequence in either FASTA or FASTQ format
		if qualities is None:
			# FASTA
			print('>%s\n%s%s' % (desc, initial, seq), file=outfile)
		else:
			assert len(seq) == len(qualities)
			# FASTQ
			print('@%s\n%s%s\n+\n%s' % (desc, initial, seq, qualities), file=outfile)

	stats.n = n
	print_statistics(options.adapters, stats)

if __name__ == '__main__':
	#import cProfile as profile
	#profile.run('main()', 'cutadapt.prof')
	main()

"""
Interpreting the result of a semiglobal alignment between the adapter and the read sequences
============================================================================================

There are nine cases, which can be grouped into four categories.

A: character of the adapter sequence (r1)
R: character of the read sequence    (r2)
-: gap symbol

The middle of the alignment is always like this:
AAAA
RRRR

For the part of that is before the middle and for the part that is after the middle,
there are three possibilities each (making 3*3=9)

A  and -  and  'nothing'
-      R

Grouping by semantics of those alignments, we get the following three categories.


1. The adapter covers or parts of it cover the entire read
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

a)
AAAA
RRRR

b)
AAAA
RR--

c)
AAAA
--RR

1d)
AAAA
-RR-

2. The adapter is at the end of the read
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

a)
---AAA
RRRRRR

b)
---AAAA
RRRRR--

3. The adapter is in the middle of the read
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

---AAA---
RRRRRRRRR

4. The adapter is in the beginning of the read
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

a)
AAAA----
RRRRRRRR

b)
AAAA----
--RRRRRR
"""
