[tox]
envlist = ruff,black,py310,py311,py312,py313,mypy,docs
isolated_build = True

[testenv]
deps =
    coverage
    pytest
    pytest-timeout
    pytest-mock
setenv =
    PYTHONDEVMODE = 1
    PIP_ONLY_BINARY = :all:
commands =
    coverage run -m pytest --doctest-modules --pyargs cutadapt tests
    coverage combine -q
    coverage report
    coverage xml

[testenv:docs]
basepython = python3.10
skip_install = true
deps = -r doc/requirements.txt
commands = sphinx-build -W -b html -d {envtmpdir}/doctrees doc {envtmpdir}/html

[testenv:ruff]
basepython = python3.10
deps = ruff
skip_install = true
commands = ruff check src/ tests/ setup.py

[testenv:mypy]
basepython = python3.10
deps = mypy
commands = mypy src/

[testenv:black]
deps = black==26.5.1
skip_install = true
commands = black --check src/ tests/ setup.py
